spring.application.name=content-search-service
spring.elasticsearch.uris=http://localhost:9200
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
server.error.include-message=always
